domain: excytin_demo

global_defaults:
  permanent_environment:
    name: "excytin-demo-databases"
    compose: "compose/databases.compose.yml"

  prompts:
    instruction: "instructions/excytin_demo.j2"
    assistant: "assistants/inspect_assistant.j2"

  max_steps: 15

  aggregation: max

  tools:
    bash:
      timeout: 180
    python:
      timeout: 180
