trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  MAJOR: 0
  MINOR: 2
  PATCH: $[counter(format('{0}.{1}', variables['MAJOR'], variables['MINOR']), 0)]

name: SABER-Release-$(MAJOR).$(MINOR).$(PATCH)

steps:
  - template: /.pipelines/python-build-test-steps.yml
  - template: /.pipelines/python-publish-steps.yml
