import asyncio
import json
import re
import os
import random
from typing import Dict, List, Tuple, Union
from fastmcp import Client
from autogen import OpenAIWrapper
from azure.ai.inference import ChatCompletionsClient
from azure.core.credentials import AzureKeyCredential
from utils.agent_utils import msging, call_llm, call_llm_foundry, update_model_usage
from config.llm_config import CONFIG_LIST, filter_config_list
import logfire

# Configure logfire for this module
logfire.configure()

# Get the directory containing react examples
curr_path = os.path.dirname(os.path.abspath(__file__))
react_examples_path = os.path.join(os.path.dirname(curr_path), "legacy_agents", "react_examples")

BASE_PROMPT = """You are a security analyst. 
You need to answer a given security question by querying the database.
The logs are stored in a MySQL database, you can use SQL queries to retrieve entries as needed.
Note there are more than 20 tables in the database, so you may need to explore the schema or check example entries to understand the database structure.

Your response should always be a thought-action pair:
Thought: <your reasoning>
Action: <your SQL query>

In Thought, you can analyse and reason about the current situation, 
Action can be one of the following: 
(1) execute[<your query>], which executes the SQL query
(2) submit[<your answer>], which is the final answer to the question

Below are some demonstrations. Note that `Observation` denotes the returned logs from the database.
Many of the returned logs are reduced for brevity (replaced with `...`).
"""

O1_PROMPT = """You are a security analyst working on investigating a security incident. 
You need to answer a given question about the security incident by querying the database of security logs provided to you.
The logs are stored in a MySQL database, you can use SQL queries to retrieve entries as needed.
Note there are more than 20 tables in the database, so you may need to explore the schema or check example entries to understand the database structure.

A security incident is composed of a group of related alerts connected by data elements or entities that are shared between the alerts such as User accounts, Hosts, Mailboxes, IP addresses, Files, Cloud applications, Processes, URLs etc. Alerts are signals that result from various threat detection activities. These signals indicate the occurrence of malicious or suspicious events in your environment. Besides the security alert signals, you can also find additional information in the raw logs like device events, user activities, network traffic, etc. 

The best way to approach the question is to start from the alert(s) that are part of the security incident and then explore the related logs to understand the context of the incident. If the security incident table is available to you, first thing to do should be to find all the information about the given incident from the security incident table. 

Other important tables to look at are the alert tables, which contains alerts and other additional information that was generated by the security monitoring tools. Once you find the alerts that are part of the security incident, you can explore the entities that are shared between the alerts to understand the context of the incident. These entities can be further used to find additional information from the logs and even alerts that you might have missed.

Your response should always be a thought-action pair:
Thought: <your reasoning>
Action: <your SQL query>

In Thought, you can analyse and reason about the current situation, 
Action can be one of the following: 
(1) execute[<your sql query>], which executes the SQL query. For example, execute[DESCRIBE table_name].
(2) submit[<your answer>], which is the final answer to the question

You should only give one thought-action per response. The action from your response will be executed and the result will be shown to you.
Follow the format "Thought: ....\nAction: ...." exactly.

Below are some demonstrations. Note that `Observation` denotes the returned logs from the database.
Many of the returned logs are reduced for brevity (replaced with `...`).
"""

R1_PROMPT = """You are a security analyst. 
You need to interact with a database with MYSQL queries to collect info and then answer a given security question.
The logs are stored in a MySQL database, you can use SQL queries to retrieve entries as needed.
Note there are more than 20 tables in the database, so you may need to explore the schema or check example entries to understand the database structure.

In you response, you should give your thoughts and actions. The reasoning process and action are enclosed within <think> </think> and <answer> </answer> tags,
You should ONLY have ONE action per response in the <answer> </answer> block, it can be one of the following based on your reasoning:
(1) <answer>execute[<your sql query>]</answer>, which executes the SQL query. For example, execute[DESCRIBE table_name]. You should give sql queries to explore the schema and acquire information.
(2) <answer>submit[<your answer>]</answer>, which submits the final answer to the question. When you believe you have enough information to answer the question, you can submit your answer.

Please do not do excessive reasoning. Briefly reason about the current situation and then give your action quickly. DO NOT make assumptions about the data that are not observed in the logs. Be conside and precice in your response.

Below are some demonstrations. Note that `Observation` denotes the returned logs from the database.
Many of the returned logs are reduced for brevity (replaced with `...`).
"""

# Load ReAct examples if they exist
if os.path.exists(react_examples_path):
    for i, file in enumerate(sorted(os.listdir(react_examples_path))):
        if file.endswith('.txt'):
            with open(os.path.join(react_examples_path, file), "r") as f:
                example_content = f.read()
                BASE_PROMPT += f"\nExample {i+1}: \n" + example_content + "\n" + "-"*50
                O1_PROMPT += f"\nExample {i+1}: \n" + example_content + "\n" + "-"*50
                R1_PROMPT += f"\nExample {i+1}: \n" + example_content + "\n" + "-"*50

    BASE_PROMPT = BASE_PROMPT.rstrip("-").strip()
    O1_PROMPT = O1_PROMPT.rstrip("-").strip()
    R1_PROMPT = R1_PROMPT.rstrip("-").strip()


class MCPReActReflexionAgent:
    """ReAct Reflexion agent that interacts with the Excytin Bench MCP server with self-reflection capabilities."""
    
    def __init__(self,
                 server_path: str,
                 config_list: List[Dict],
                 cache_seed: int = 41,
                 max_steps: int = 15,
                 submit_summary: bool = False,
                 temperature: float = 0,
                 retry_num: int = 10,
                 retry_wait_time: int = 5,
                 ):
        """
        Initialize the MCP ReAct Reflexion Agent.
        
        Args:
            server_path: Path to the MCP server script
            config_list: LLM configuration list
            cache_seed: Cache seed for reproducibility
            max_steps: Maximum number of steps
            submit_summary: Whether to submit summary at the end
            temperature: LLM temperature
            retry_num: Number of retries for LLM calls
            retry_wait_time: Wait time between retries
        """
        self.server_path = server_path
        self.cache_seed = cache_seed
        self.config_list = config_list
        self.temperature = temperature
        self.max_steps = max_steps
        self.submit_summary = submit_summary
        self.retry_num = retry_num
        self.retry_wait_time = retry_wait_time
        self.step_count = 0
        self.total_usage = {}
        self.replay_buffer = []  # Store previous trials for reflection
        
        # Initialize MCP client
        self.mcp_client = Client(server_path)
        
        # Adjust temperature for specific models
        if "o4" in config_list[0]['model']:
            self.temperature = 1
        
        # Initialize LLM client
        if "ai_foundry" in config_list[0].get('api_type', ''):
            self.llm_client = ChatCompletionsClient(
                endpoint=config_list[0]['endpoint'],
                credential=AzureKeyCredential(config_list[0]['api_key']),
                seed=self.cache_seed
            )
        else:
            self.llm_client = OpenAIWrapper(config_list=config_list, cache_seed=cache_seed)
        
        # Set system prompt based on model type
        sys_prompt = BASE_PROMPT
        if any(model_type in config_list[0]['model'] for model_type in ["o1", "o3", "o4"]):
            sys_prompt = O1_PROMPT
        elif any(model_type in config_list[0]['model'] for model_type in ["r1", "R1", "qwen3"]):
            sys_prompt = R1_PROMPT
            
        self.messages = [{"role": "system", "content": sys_prompt}]
        
        # No system prompt for some models
        if any(model_type in config_list[0]['model'] for model_type in ["r1", "R1", "qwen3"]):
            self.messages = [{"role": "system", "content": sys_prompt}]
            print("Using R1/DeepSeek-style prompt with examples and reflection")
    
    @property
    def name(self):
        return "MCPReActReflexionAgent"
    
    def _call_llm(self, messages):
        """Call the LLM with the given messages."""
        if "ai_foundry" in self.config_list[0].get('api_type', ''):
            response = call_llm_foundry(
                client=self.llm_client,
                model=self.config_list[0]['model'],
                messages=messages,
                retry_num=self.retry_num,
                retry_wait_time=self.retry_wait_time,
                temperature=self.temperature,
                stop=["Observation:", "observation:", '</answer>'],
            )
            update_model_usage(self.total_usage, model_name=response.model, 
                             usage_dict=response.usage.as_dict())
        else:
            response = call_llm(
                client=self.llm_client,
                model=self.config_list[0]['model'],
                messages=messages,
                retry_num=self.retry_num,
                retry_wait_time=self.retry_wait_time,
                temperature=self.temperature,
                stop=["Observation:", "observation:"]
            )
            update_model_usage(self.total_usage, model_name=response.model, 
                             usage_dict=response.usage.model_dump())
        return response.choices[0].message.content
    
    def reflect(self):
        """Generate reflection based on previous trials."""
        # If no replays return
        if len(self.replay_buffer) == 0:
            print("No replays to reflect on")
            return None

        # Sample previous trials for reflection
        previous_trials_count = min(3, len(self.replay_buffer))
        if len(self.replay_buffer) <= previous_trials_count:
            replays = self.replay_buffer
        else:
            replays = random.sample(self.replay_buffer, previous_trials_count)
        
        # Extract reflective text from replays
        REFLECT_PROMPT = f"""You are an advanced reasoning agent that can improve based on self reflection. You will be given a previous reasoning trial in which you were given a question to answer. You were unsuccessful in answering the question either because you guessed the wrong answer with submit[<answer>] or there is a phrasing discrepancy with your provided answer and the answer key. In a few sentences, Diagnose a possible reason for failure or phrasing discrepancy and devise a new, concise, high level plan that aims to mitigate the same failure. Use complete sentences.
        Previous trials:
        {[f"Trial {i}, Reward: {replay['reward']}, Transcript: {replay['messages']}" for i, replay in enumerate(replays)]}
        Reflection:
        """
        
        try:
            # Truncate prompt if too long to avoid context length issues
            reflection = self._call_llm(messages=[msging(REFLECT_PROMPT[:120000])])
            print(f"\n[REFLECTION] Generated reflection based on {len(replays)} previous trials")
            print(f"Reflection: {reflection}")
            return reflection
        except Exception as e:
            print(f"Failed to generate reflection: {e}")
            return None
    
    def _parse_action(self, action: str) -> Tuple[str, bool]:
        """Parse the action string to extract SQL query or answer and determine if it's a submission."""
        # Remove backticks
        action = action.replace("`", "")
        
        # Check for submit action
        if "submit[" in action:
            pattern = r'submit\[(.*)\]'
            matches = re.findall(pattern, action, re.DOTALL)
            if matches:
                return matches[0], True
            return action, True
        
        # Check for execute action
        if "execute[" in action:
            pattern = r'execute\[(.*)\]'
            matches = re.findall(pattern, action, re.DOTALL)
            if matches:
                query = matches[0]
                # Remove semicolon if present
                if ";" in query:
                    query = query[:query.index(";")]
                return query, False
            
        return action, False
    
    async def _initialize_session(self, attack: str, q_idx: int = 0, max_steps: int = 100,
                                  split: str = "test", use_full_db: bool = False, layer: str = "alert"):
        """Initialize the MCP session."""
        try:
            result = await self.mcp_client.call_tool("initialize_context", {
                "attack": attack,
                "max_steps": max_steps,
                "split": split,
                "use_full_db": use_full_db,
                "layer": layer,
                "q_idx": q_idx
            })
            print(f"Session initialized: {result.data if hasattr(result, 'data') else result}")
            return True
        except Exception as e:
            print(f"Failed to initialize session: {e}")
            return False
    
    async def _get_current_question(self):
        """Get the current question from the MCP server."""
        try:
            result = await self.mcp_client.call_tool("get_current_question", {})
            result_data = result.data if hasattr(result, 'data') else result
            return result_data.get('question', {})
        except Exception as e:
            print(f"Failed to get current question: {e}")
            return None
    
    async def _execute_query(self, query: str):
        """Execute a SQL query via the MCP server."""
        try:
            result = await self.mcp_client.call_tool("query_sql_database", {
                "query": query
            })
            result_data = result.data if hasattr(result, 'data') else result
            return result_data.get('observation', f"Query executed: {query}")
        except Exception as e:
            print(f"Failed to execute query: {e}")
            return f"Error executing query: {str(e)}"
    
    async def _submit_answer(self, answer: str):
        """Submit an answer via the MCP server."""
        try:
            result = await self.mcp_client.call_tool("submit_answer", {
                "answer": answer
            })
            result_data = result.data if hasattr(result, 'data') else result
            return result_data
        except Exception as e:
            print(f"Failed to submit answer: {e}")
            return {"error": str(e)}
    
    async def act(self, observation: str = None):
        """
        Generate an action based on the current observation.
        
        Args:
            observation: Current observation (can be None for initial step)
            
        Returns:
            Tuple of (action, is_submit)
        """
        # Add observation to messages if provided
        if observation is not None:
            self._add_message(observation, role="user")
        
        # Generate response from LLM
        response = self._call_llm(messages=self.messages)
        
        # Print agent's thinking with clear formatting
        print("\n" + "="*60)
        print(f"REFLEXION AGENT STEP {self.step_count + 1} - THINKING:")
        print("="*60)
        print(response)
        print("="*60)
        
        # Add summary prompt if we're at max steps
        if self.step_count >= self.max_steps - 1 and self.submit_summary:
            summary_prompt = "You have reached maximum number of steps. Please summarize your findings of key information, and submit them."
            self._add_message(summary_prompt, role="system")
        
        # Parse thought and action
        split_str = "\nAction:"
        if any(model_type in self.config_list[0]['model'] for model_type in ["r1", "R1", "qwen3"]):
            split_str = "<answer>"
        
        if "**Action:**" in response:
            split_str = "\n**Action:**"
        
        try:
            thought, action = response.strip().split(split_str)
            action = action.replace("<answer>", "").replace("</answer>", "")
            self._add_message(response.strip(), role="assistant")
        except:
            print("\n[RETRY] Splitting action failed, getting action separately:")
            thought = response.strip()
            action = self._call_llm(self.messages + [msging(f"{thought}\nAction:")])
            print(f"Action: {action}")
            action = action.strip()
            action = action.replace("<answer>", "").replace("</answer>", "")
            if "Thought" not in thought:
                thought = f"Thought: {thought}"
            self._add_message(f"{thought}\nAction:{action}", role="assistant")
        
        self.step_count += 1
        
        # Parse the action
        parsed_action, is_submit = self._parse_action(action)
        
        return parsed_action, is_submit
    
    async def run_episode(self, attack: str, q_idx: int = 0, max_steps: int = None,
                          split: str = "test", use_full_db: bool = False, layer: str = "alert"):
        """
        Run a complete episode for a given attack and question.
        
        Args:
            attack: Attack identifier
            q_idx: Question index
            max_steps: Maximum steps (uses agent's max_steps if None)
            split: Data split to use
            use_full_db: Whether to use full database
            layer: Layer type
            
        Returns:
            Dictionary with episode results
        """
        if max_steps is None:
            max_steps = self.max_steps
        
        async with self.mcp_client:
            # Initialize session
            if not await self._initialize_session(attack, q_idx, max_steps, split, use_full_db, layer):
                return {"error": "Failed to initialize session"}
            
            # Get the initial question
            question = await self._get_current_question()
            if question is None:
                return {"error": "Failed to get current question"}
            
            print(f"Question: {json.dumps(question, indent=2)}")
            
            # Extract question text
            if isinstance(question, dict):
                question_text = question.get('question', str(question))
            else:
                question_text = str(question)
            
            # Start with the question as initial observation
            observation = f"Question: {question_text}"
            
            episode_history = []
            final_result = None
            
            while self.step_count < max_steps:
                print(f"\n{'='*60}")
                print(f"REFLEXION STEP {self.step_count + 1}/{max_steps}")
                print(f"{'='*60}")
                print(f"Current observation: {observation}")
                print(f"{'='*60}")
                
                # Get action from agent
                action, is_submit = await self.act(observation)
                
                episode_history.append({
                    "step": self.step_count,
                    "action": action,
                    "is_submit": is_submit,
                    "messages": [msg for msg in self.messages[-2:]]  # Store last 2 messages (user + assistant)
                })
                
                print(f"\n[RESULT] Action to execute: {action}")
                print(f"[RESULT] Is submission: {is_submit}")
                
                if is_submit:
                    # Submit answer and get final result
                    final_result = await self._submit_answer(action)
                    print(f"\n{'='*60}")
                    print("FINAL SUBMISSION")
                    print(f"{'='*60}")
                    print(f"Answer: {action}")
                    print(f"Result: {final_result}")
                    print(f"{'='*60}")
                    break
                else:
                    # Execute query and get observation
                    observation = await self._execute_query(action)
                    print(f"\n[QUERY RESULT]")
                    print(f"Query: {action}")
                    print(f"Result: {observation}")
                    episode_history[-1]["observation"] = observation
            
            # Store this trial in replay buffer for future reflection
            trial_record = {
                "attack": attack,
                "question_idx": q_idx,
                "question": question,
                "messages": [msg['content'] for msg in self.messages],
                "final_result": final_result,
                "reward": 1 if final_result and not final_result.get('error') else 0,  # Simple reward
                "total_steps": self.step_count
            }
            self.replay_buffer.append(trial_record)
            
            return {
                "attack": attack,
                "question_idx": q_idx,
                "question": question,
                "episode_history": episode_history,
                "final_result": final_result,
                "total_steps": self.step_count,
                "usage_summary": self.total_usage,
                "replay_buffer_size": len(self.replay_buffer)
            }
    
    def _add_message(self, msg: str, role: str = "user"):
        """Add a message to the conversation history."""
        self.messages.append(msging(msg, role))
    
    def get_logging(self):
        """Get logging information."""
        return {
            "messages": self.messages,
            "usage_summary": self.total_usage,
            "replay_buffer_size": len(self.replay_buffer),
        }
    
    def print_conversation_history(self):
        """Print the full conversation history for debugging."""
        print("\n" + "="*80)
        print("REFLEXION AGENT CONVERSATION HISTORY")
        print("="*80)
        for i, msg in enumerate(self.messages):
            print(f"\n--- Message {i+1} ({msg['role']}) ---")
            print(msg['content'])
        print("="*80)
    
    def reset(self, change_seed: bool = True):
        """Reset the agent state."""
        if change_seed:
            self.cache_seed += 1
        
        # Reinitialize LLM client with new seed
        if "ai_foundry" in self.config_list[0].get('api_type', ''):
            self.llm_client = ChatCompletionsClient(
                endpoint=self.config_list[0]['endpoint'],
                credential=AzureKeyCredential(self.config_list[0]['api_key']),
                seed=self.cache_seed
            )
        elif "azure" in self.config_list[0].get('api_type', ''):
            self.llm_client = OpenAIWrapper(config_list=self.config_list, cache_seed=self.cache_seed)
        
        self.step_count = 0
        
        # Reset system prompt
        sys_prompt = BASE_PROMPT
        if any(model_type in self.config_list[0]['model'] for model_type in ["o1", "o3", "o4"]):
            sys_prompt = O1_PROMPT
        elif any(model_type in self.config_list[0]['model'] for model_type in ["r1", "R1", "qwen3"]):
            sys_prompt = R1_PROMPT
            
        self.messages = [{"role": "system", "content": sys_prompt}]
        
        # Time to reflect on previous experiences
        reflection = self.reflect()
        
        # Add reflection to messages
        if reflection:
            self._add_message(reflection, role="system")
        
        self.total_usage = {}


# Example usage and testing function
async def test_mcp_react_reflexion_agent():
    """Test function for the MCP ReAct Reflexion Agent."""
    # Example config - you'll need to provide your actual config
    model_name = "gpt-4o"  # Default eval model, can be overridden
    config_list = filter_config_list(CONFIG_LIST, model_name)
    
    # Initialize agent
    agent = MCPReActReflexionAgent(
        server_path="excytin_bench_server.py",
        config_list=config_list,
        max_steps=10
    )
    
    # Run multiple episodes to test reflection
    for i in range(2):
        print(f"\n{'='*80}")
        print(f"RUNNING EPISODE {i+1}")
        print(f"{'='*80}")
        
        result = await agent.run_episode(
            attack="incident_5",
            q_idx=0,
            max_steps=10,
            use_full_db=False
        )
        
        print(f"Episode {i+1} Results:")
        print(json.dumps(result, indent=2, default=str))
        
        # Reset for next episode
        agent.reset()


if __name__ == "__main__":
    asyncio.run(test_mcp_react_reflexion_agent())
