version: '3.8'
services:
  saber-excytin-incident-5:
    image: mysql:8.0
    command: --secure-file-priv=/var/lib/mysql --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: env_monitor_db
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306
    networks:
    - excytin_isolated
networks:
  excytin_isolated:
    driver: bridge
    internal: true
    ipam:
      config:
      - subnet: 172.20.100.0/24
